version: '3.7'
services:
  app:
    container_name: app
    working_dir: /app
    image: node:lts
    volumes:
      - ./app:/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      - ${NEXTJS_PORT}:3000
    depends_on:
      - mysql
  api:
    container_name: api
    image: golang:1.20.4-bullseye
    volumes:
      - ./api:/api/
    working_dir: /api
    ports:
        - ${GO_PORT}:${GO_PORT}
    # ホットリロード
    command: /bin/bash -c "go get -u github.com/cosmtrek/air && go build -o /go/bin/air github.com/cosmtrek/air && air -c .air.toml"
    # これでもいい
    # command: /bin/bash -c "go mod tidy && go run main.go"
    # command: >
    #   /bin/bash -c "
    #     go mod tidy &&
    #     go run main.go
    #   "
    tty: true
    # networks: [restaurant-network]
    # environment:
    #     - HOST_IP=${HOST_IP}
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - GO_PORT=${GO_PORT}
      - NEXTJS_PORT=${NEXTJS_PORT}
    depends_on:
      - mysql
  mysql:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
